remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: Unix/Linux Sysadmin Command Reference Guide
description: A comprehensive guide for system administration commands
markdown: kramdown
kramdown:
  toc_levels: 1..3
